<?php

/**
 * @file
 * Contains as_basic_pages.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_basic_pages_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_basic_pages module.
    case 'help.page.as_basic_pages':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains configurations for A&amp;S Basic Pages') . '</p>';
      return $output;

    default:
  }
}
