<?php

/**
 * @file
 * Contains as_topics.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_tipocs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_topics module.
    case 'help.page.as_topics':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains configurations for topics and disciplines as used on as.cornell.edu, and a migration group to import topics and disciplines taxonomy terms from Drupal 7 into Drupal 8') . '</p>';
      return $output;

    default:
  }
}
