<?php
// DRUPAL-VM
$sites['scholsie.as.fellaini.local'] = 'default';
$sites['scholsie.dept1.fellaini.local'] = 'dept1';
$sites['scholsie.dept2.fellaini.local'] = 'dept2';
// DEV
$sites['dev.as.cornell.edu'] = 'as';
$sites['deptdev.as.cornell.edu'] = 'pma';
//STAGE
$sites['stage.as.cornell.edu'] = 'as';
//PROD
$sites['prod.as.cornell.edu'] = 'prod';
$sites['as.cornell.edu'] = 'as';
$sites['arts.cornell.edu'] = 'as';
$sites['people.as.cornell.edu'] = 'people';
$sites['communications.as.cornell.edu'] = 'communications';
$sites['anthropology.cornell.edu'] = 'anthro';
$sites['latino.cornell.edu'] = 'latino';
$sites['linguistics.cornell.edu'] = 'linguistics';
$sites['pma.cornell.edu'] = 'pma';
$sites['neareasternstudies.cornell.edu'] = 'nes';
$sites['chemistry.cornell.edu'] = 'chem';
$sites['africana.cornell.edu'] = 'africana';
$sites['religious-studies.cornell.edu'] = 'religiousstudies';
$sites['jewishstudies.cornell.edu'] = 'jewishstudies';
$sites['history.cornell.edu'] = 'history';
$sites['philosophy.cornell.edu'] = 'phil';
$sites['government.cornell.edu'] = 'govt';
$sites['ecologyandevolution.cornell.edu'] = 'eeb';
$sites['classics.cornell.edu'] = 'classics';
$sites['asianstudies.cornell.edu'] = 'asianstudies';
$sites['physics.cornell.edu'] = 'physics';
$sites['english.cornell.edu'] = 'english';
$sites['caps.cornell.edu'] = 'caps';
$sites['complit.cornell.edu'] = 'complit';
$sites['sts.cornell.edu'] = 'sts';
$sites['asianamericanstudies.cornell.edu'] = 'aas';
$sites['arthistory.cornell.edu'] = 'arth';
$sites['nbb.cornell.edu'] = 'bionb';
$sites['knight.as.cornell.edu'] = 'knight';
$sites['german.cornell.edu'] = 'gerst';
$sites['archaeology.cornell.edu'] = 'archaeology';
$sites['music.cornell.edu'] = 'music';
$sites['societyhumanities.as.cornell.edu'] = 'sochum';
$sites['economics.cornell.edu'] = 'econ';
$sites['romancestudies.cornell.edu'] = 'romance';
$sites['fgss.cornell.edu'] = 'fgss';
$sites['lgbt.cornell.edu'] = 'lgbt';
$sites['americanstudies.cornell.edu'] = 'americanstudies';
$sites['sociology.cornell.edu'] = 'sociology';
$sites['psychology.cornell.edu'] = 'psych';
$sites['igcs.cornell.edu'] = 'igcs';
$sites['math.cornell.edu'] = 'math';
$sites['medievalstudies.cornell.edu'] = 'medieval';
$sites['astro.cornell.edu'] = 'astro';
$sites['research.astro.cornell.edu'] = 'astroresearch';
$sites['milstein-program.as.cornell.edu'] = 'milstein';
$sites['lrc.cornell.edu'] = 'lrc';
$sites['baroqueorgan.cornell.edu'] = 'organ';
$sites['mediastudies.as.cornell.edu'] = 'mediastudies';
$sites['cinema.cornell.edu'] = 'cinema';
$sites['carlsaganinstitute.cornell.edu'] = 'sagan';
$sites['rural.as.cornell.edu'] = 'rural';
$sites['cder.as.cornell.edu'] = 'dber';
$sites['sct.cornell.edu'] = 'sct';
$sites['inequality.cornell.edu'] = 'inequality';
$sites['frenchstudies.cornell.edu'] = 'frenchstudies';
$sites['cogsci.cornell.edu'] = 'cogsci';
$sites['icm.as.cornell.edu'] = 'icm';

// DEVVY THINGS
$sites['budgetdev.as.cornell.edu'] = 'budget';
$sites['cogsci.as.cornell.edu'] = 'cogsci';
