<?php

/**
 * @file
 * Contains as_toc_pages.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function as_toc_pages_generate_link_markup($link_title) {
  $markup = NULL;
    // get variables from array being passed to this function
    //dump($section_label_data);
    $link_name = preg_replace('/\W+/','-',strtolower(strip_tags($link_title)));;
    // Create the markup
    $markup = $markup . "<li><a href='#" . $link_name . "'>" . $link_title . "</a></li>";

    return $markup;
  }


function as_toc_pages_generate_card_link_markup($link_title,$page_value) {
  $markup = NULL;
    // get variables from array being passed to this function
    //dump($section_label_data);
    $link_name = preg_replace('/\W+/','-',strtolower(strip_tags($link_title)));;
    // Create the markup
    $markup = $markup . "<li><a href='". $page_value . "#" . $link_name . "'>" . $link_title . "</a></li>";

    return $markup;
  }


/**
 * Implements hook_help().
 */
function as_toc_pages_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_toc_pages module.
    case 'help.page.as_toc_pages':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains configurations for TOC page content type and plugins for blocks to display in asides and cards.  Replaces Modal Pages.') . '</p>';
      return $output;

    default:
  }
}
