<?php

/**
 * @file
 * Contains as_slideshow.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_slideshow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_slideshow module.
    case 'help.page.as_slideshow':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains configurations for slides content type and slideshow view as used on A&amp;S Screens') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function as_slideshow_theme() {
  return [
    'as_slideshow' => [
      'render element' => 'children',
    ],
  ];
}
