<?php

/**
 * Implements hook_views_data_alter().
 */
function views_autorefresh_views_data_alter(array &$data) {
  // Add our autorefresh area to Global.
  $data['views']['autorefresh'] = [
    'title' => t('Autorefresh'),
    'help' => t('Enable autorefresh for this view. NOTE: This will automatically turn AJAX support ON.'),
    'area' => [
      'id' => 'views_autorefresh_area',
    ],
  ];

}
