<?php

/**
 * @file
 * Contains as_modal_pages.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function as_modal_pages_generate_link_markup($link_title) {
  $markup = NULL;
    // get variables from array being passed to this function
    //dump($section_label_data);
    $link_name = preg_replace('/\W+/','-',strtolower(strip_tags($link_title)));;
    // Create the markup
    $markup = $markup . "<li><a href='#" . $link_name . "'>" . $link_title . "</a></li>";

    return $markup;
  }


function as_modal_pages_generate_card_link_markup($link_title,$page_value) {
  $markup = NULL;
    // get variables from array being passed to this function
    //dump($section_label_data);
    $link_name = preg_replace('/\W+/','-',strtolower(strip_tags($link_title)));;
    // Create the markup
    $markup = $markup . "<li><a href='". $page_value . "#" . $link_name . "'>" . $link_title . "</a></li>";

    return $markup;
  }

/**
 * Implements hook_help().
 */
function as_modal_pages_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_modal_pages module.
    case 'help.page.as_modal_pages':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains configurations for Modal Page content type and block plugin to provide in-page navigation.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function as_modal_pages_theme() {
  return [
    'as_modal_pages' => [
      'render element' => 'children',
    ],
  ];
}
