<?php

/**
 * @file
 * Contains as_stats.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_stats_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_stats module.
    case 'help.page.as_stats':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains migrations for stats content type as used on as.cornell.edu from Drupal 7 into Drupal 8') . '</p>';
      return $output;

    default:
  }
}
