<?php

/**
 * @file
 * Contains as_migrate_people.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_migrate_people_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_migrate_people_descriptions module.
    case 'help.page.as_migrate_people':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrates people from Drupal 7 to Drupal 8.  Migrates summary field collections to paragraphs, and Images to Media References.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function as_migrate_people_theme() {
  return [
    'as_migrate_people' => [
      'render element' => 'children',
    ],
  ];
}
