# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysqldb:
    type: "mysql:10.0"
    disk: 2048
    configuration:
        schemas:
            - firstdb
            - departmentsdb
            - peopledb
            - samldb
            - scholsiedb
            - dept1
            - dept2
            - people7db
            - saml7db
        endpoints:
            first:
                default_schema: firstdb
                privileges:
                    firstdb: admin
            departments:
                default_schema: departmentsdb
                privileges:
                    departmentsdb: admin
            people:
                default_schema: peopledb
                privileges:
                    peopledb: admin
            saml:
                default_schema: samldb
                privileges:
                    samldb: admin
            scholsie:
                default_schema: scholsiedb
                privileges:
                    scholsiedb: admin
            dept1:
                default_schema: dept1db
                privileges:
                    dept1db: admin
            dept2:
                default_schema: dept2db
                privileges:
                    dept2db: admin
            people7:
                default_schema: people7db
                privileges:
                    people7db: admin
            saml7:
                default_schema: saml7db
                privileges:
                    saml7db: admin

#rediscache:
#    type: "redis:3.0"
#
#solrsearch:
#    type: "solr:4.10"
#    disk: 1024
