<?php

/**
 * @file
 * Contains as_migrate_articles.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_migrate_articles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_migrate_articles module.
    case 'help.page.as_migrate_articles':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate A&S articles from Drupal 7 to Drupal 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function as_migrate_articles_theme() {
  return [
    'as_migrate_articles' => [
      'render element' => 'children',
    ],
  ];
}
